export const emojiDictionary = {
  "😀": "Grinning Face",
  "😗": "Kissing Face",
  "😋": "Face Savoring Food",
  "😴": "Sleeping Face",
  "👿": "Angry Face with Horns",
  "🎤": "Mic",
  "💘": "Heart with Arrow",
  "💓": "Beating Heart",
  "💔": "Broken Heart",
  "💚": "Green Heart",
  "🌀": "Cyclone",
  "♣️": "Club Suit",
  "🔇": "Muted Speaker",
  "🔔": "Bell",
  "🚮": "Litter in Bin Sign",
  "📵": "No Mobile Phones",
  "⬆️": "Up Arrow",
  "➡️ ": "Right Arrow",
  "⬇️": "Down Arrow",
  "⬅️": "Left Arrow",
  "⚛️": "Atom Symbol",
  "▶️": "Play Button",
  "⏸️": "Pause Button",
  "🎦": "Cinema",
  "📴": "Mobile Phone Off",
  "♾️": "Infinity",
  "♻️": "Recycling Symbol",
  " ©️": "Copyright",
  "🔺": "Red Triangle Pointed Up",
};
